<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "trb_pi_team2"
 *
 * Auto generated by Extension Builder 2014-08-16
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'TRB Plugin: Team 2 (fe_users)',
	'description' => 'This extension extends fe_users and adds content element for schedule and fe_user with Extbase/Fluid rendering.',
	'category' => 'plugin',
	'author' => 'Boris Günther',
	'author_email' => 'info@boris-guenther.de',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 1,
	'version' => '2.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
			'static_info_tables' => '6.1',
			'trb_basics' => '2.0',
			'trb_basics_typoscript' => '2.0',
			'trb_basics_viewhelper' => '2.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);